name: Running Code Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.7.17
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.17
    - name: Install dependencies
      working-directory: ./backend
      run: |
        pip install -r requirements.txt
        echo requirements installed  
    - name: Run tests
      working-directory: ./backend
      run: |
        python -m unittest test_api.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
